vich_uploader:
  db_driver: orm

  mappings:
    profile_file:
      uri_prefix: /uploads/userfile
      upload_destination: '%kernel.project_dir%/public/uploads/userfile'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update:   true
      delete_on_remove:   true
