services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easterapp_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: easterapp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easterapp
      MYSQL_USER: easter
      MYSQL_PASSWORD: easter
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:18
    container_name: easterapp_node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "yarn install && yarn run dev"
    build:
      context: .
      dockerfile: Dockerfile.node


volumes:
  db_data:
