<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8Gz5nHy' shared service.

return $this->privates['.service_locator.8Gz5nHy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'featureRepository' => ['privates', 'App\\Repository\\FeatureRepository', 'getFeatureRepositoryService.php', true],
], [
    'featureRepository' => 'App\\Repository\\FeatureRepository',
]);
