<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sgSz4uu' shared service.

return $this->privates['.service_locator.sgSz4uu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'mailManager' => ['privates', 'App\\Service\\MailManager', 'getMailManagerService.php', true],
    'tokenGenerator' => ['privates', 'security.csrf.token_generator', 'getSecurity_Csrf_TokenGeneratorService.php', true],
], [
    'mailManager' => 'App\\Service\\MailManager',
    'tokenGenerator' => '?',
]);
