<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zxE9AQG' shared service.

return $this->privates['.service_locator.zxE9AQG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'project' => ['privates', '.errored..service_locator.zxE9AQG.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.zxE9AQG": it references class "App\\Entity\\Project" but no such service exists.'],
    'projectCalculator' => ['privates', 'App\\Service\\ProjectCalculator', 'getProjectCalculatorService.php', true],
], [
    'project' => 'App\\Entity\\Project',
    'projectCalculator' => 'App\\Service\\ProjectCalculator',
]);
