<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WJmn2xJ' shared service.

return $this->privates['.service_locator.WJmn2xJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'project' => ['privates', '.errored..service_locator.WJmn2xJ.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.WJmn2xJ": it references class "App\\Entity\\Project" but no such service exists.'],
    'projectCalculator' => ['privates', 'App\\Service\\ProjectCalculator', 'getProjectCalculatorService.php', true],
    'projectFeatureRepos' => ['privates', 'App\\Repository\\ProjectFeatureRepository', 'getProjectFeatureRepositoryService.php', true],
    'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService.php', true],
    'quotationRepository' => ['privates', 'App\\Repository\\QuotationRepository', 'getQuotationRepositoryService.php', true],
], [
    'project' => 'App\\Entity\\Project',
    'projectCalculator' => 'App\\Service\\ProjectCalculator',
    'projectFeatureRepos' => 'App\\Repository\\ProjectFeatureRepository',
    'projectRepository' => 'App\\Repository\\ProjectRepository',
    'quotationRepository' => 'App\\Repository\\QuotationRepository',
]);
