<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.8TCuDTJ.App\Entity\Feature' shared service.

$this->throw('Cannot autowire service ".service_locator.8TCuDTJ": it references class "App\\Entity\\Feature" but no such service exists.');
