<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.WJmn2xJ.App\Entity\Project' shared service.

$this->throw('Cannot autowire service ".service_locator.WJmn2xJ": it references class "App\\Entity\\Project" but no such service exists.');
