<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Ar0VEqn.App\Entity\Category' shared service.

$this->throw('Cannot autowire service ".service_locator.Ar0VEqn": it references class "App\\Entity\\Category" but no such service exists.');
