<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\ProjectCalculator' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/ProjectCalculator.php';

return $this->privates['App\\Service\\ProjectCalculator'] = new \App\Service\ProjectCalculator(($this->privates['App\\Repository\\QuotationRepository'] ?? $this->load('getQuotationRepositoryService.php')), ($this->privates['App\\Repository\\ProjectRepository'] ?? $this->load('getProjectRepositoryService.php')), ($this->privates['App\\Repository\\ProjectFeatureRepository'] ?? $this->load('getProjectFeatureRepositoryService.php')));
