<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FnhnRVd' shared service.

return $this->privates['.service_locator.FnhnRVd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'projectCalculator' => ['privates', 'App\\Service\\ProjectCalculator', 'getProjectCalculatorService.php', true],
    'projectFeature' => ['privates', '.errored..service_locator.FnhnRVd.App\\Entity\\ProjectFeature', NULL, 'Cannot autowire service ".service_locator.FnhnRVd": it references class "App\\Entity\\ProjectFeature" but no such service exists.'],
], [
    'entityManager' => '?',
    'projectCalculator' => 'App\\Service\\ProjectCalculator',
    'projectFeature' => 'App\\Entity\\ProjectFeature',
]);
