<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ar0VEqn' shared service.

return $this->privates['.service_locator.Ar0VEqn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.Ar0VEqn.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.Ar0VEqn": it references class "App\\Entity\\Category" but no such service exists.'],
    'feature' => ['privates', 'App\\Repository\\FeatureRepository', 'getFeatureRepositoryService.php', true],
    'projectFeature' => ['privates', 'App\\Repository\\ProjectFeatureRepository', 'getProjectFeatureRepositoryService.php', true],
], [
    'category' => 'App\\Entity\\Category',
    'feature' => 'App\\Repository\\FeatureRepository',
    'projectFeature' => 'App\\Repository\\ProjectFeatureRepository',
]);
