<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.FnhnRVd.App\Entity\ProjectFeature' shared service.

$this->throw('Cannot autowire service ".service_locator.FnhnRVd": it references class "App\\Entity\\ProjectFeature" but no such service exists.');
