<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPiI284J\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPiI284J/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPiI284J.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPiI284J\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPiI284J\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PiI284J',
    'container.build_id' => '612d444d',
    'container.build_time' => 1751305153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPiI284J');
